name: moviemaze_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # For making HTTP requests
  cached_network_image: ^3.2.0 # To cache and display images
  provider: ^6.0.5 # For state management (optional but useful)

  cupertino_icons: ^1.0.8
  html: ^0.15.5
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
